test:
  adapter: mysql2
  encoding: utf8
  database: hacknight
  pool: 20
  username: ruser
  password: ruser
  host: localhost
  reconnect: true
  wait_timeout: 30


development:
  adapter: mysql2
  encoding: utf8
  database: hacknight
  pool: 20
  username: ruser
  password: ruser
  host: localhost
  reconnect: true
  wait_timeout: 30